"""add_orders_idempotency_key

Revision ID: e735ed2b876f
Revises: c6e38797861c
Create Date: 2026-06-24 03:27:53.384948+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = 'e735ed2b876f'
down_revision: Union[str, None] = 'c6e38797861c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=128), nullable=False))
    op.create_unique_constraint('uq_orders_idempotency_key', 'orders', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_idempotency_key', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
