"""initial_schema

Revision ID: c6e38797861c
Revises: 
Create Date: 2026-06-24 02:53:16.876851+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = 'c6e38797861c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('asset_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_price_paise', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_active'), 'templates', ['active'], unique=False)
    op.create_index(op.f('ix_templates_language'), 'templates', ['language'], unique=False)
    op.create_index(op.f('ix_templates_theme'), 'templates', ['theme'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('role', sa.Enum('consumer', 'agent', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('agents',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commission_rate_bps', sa.Integer(), nullable=False),
    sa.Column('payout_upi_vpa', sa.String(length=100), nullable=True),
    sa.Column('payout_bank_account', sa.String(length=200), nullable=True),
    sa.Column('payout_ifsc', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', name='agent_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta_paise', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('purchase', 'spend', 'refund', 'commission', name='ledger_reason'), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_credit_ledger_idempotency_key')
    )
    op.create_index(op.f('ix_credit_ledger_created_at'), 'credit_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_ledger_reason'), 'credit_ledger', ['reason'], unique=False)
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.Enum('razorpay', name='payment_gateway'), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', name='payment_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('raw_webhook', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key')
    )
    op.create_index(op.f('ix_payments_gateway_order_id'), 'payments', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'queued', 'moderating', 'generating', 'done', 'rejected', 'refunded', 'failed', name='order_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_agent_id'), 'orders', ['agent_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_template_id'), 'orders', ['template_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'moderating', 'generating', 'done', 'rejected', 'failed', name='job_status'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('cost_paise', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moderation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_order_id'), 'generation_jobs', ['order_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_order_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_template_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_agent_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_reason'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_created_at'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_theme'), table_name='templates')
    op.drop_index(op.f('ix_templates_language'), table_name='templates')
    op.drop_index(op.f('ix_templates_active'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
